CREATE DATABASE OnlineStore

USE OnlineStore

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY,
[Name] VARCHAR(50))

CREATE TABLE Items(
ItemID INT PRIMARY KEY,
[Name] VARCHAR(50),
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID))

CREATE TABLE Cities(
CityID INT PRIMARY KEY,
[Name] VARCHAR(50))

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY,
[Name] VARCHAR(50),
Birthday DATETIME ,
CityID INT FOREIGN KEY REFERENCES Cities(CityID))

CREATE TABLE Orders(
OrderID INT PRIMARY KEY,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID))


CREATE TABLE OrderItems(
OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
ItemID INT FOREIGN KEY REFERENCES Items(ItemID),
PRIMARY KEY (OrderID, ItemID))

DROP TABLE ItemTypes
DROP TABLE Items
DROP TABLE Cities
DROP TABLE Customers
DROP TABLE Orders
DROP TABLE OrderItems