CREATE DATABASE University

USE University

CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) NOT NULL)

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber VARCHAR(50) NOT NULL,
[StudentName] VARCHAR(50) NOT NULL,
MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID))

CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY,
[SubjectName] VARCHAR(50) NOT NULL)

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATETIME2 NOT NULL,
PaymentAmount DECIMAL(8,2) NOT NULL,
StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID))

CREATE TABLE Agenda(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID),
PRIMARY KEY(StudentID, SubjectID))